### GET ALL MOVIES
GET http://localhost:4000/movies HTTP/1.1

### GET MOVIE BY ID
GET http://localhost:4000/movies/11c2ca60-efcf-11ef-b5e4-c0c28a6d8451 HTTP/1.1

### GET MOVIES BY GENRE
GET http://localhost:4000/movies?genre=Action HTTP/1.1

###CREATE A MOVIE
POST http://localhost:4000/movies HTTP/1.1
Content-Type: application/json

{
    "title": "Ana",
    "year": 1993,
    "director": "Krawczyk",
    "duration": 88,
    "poster": "https://m.media-amazon.com/images/I/81BMmrwSFOL._AC_UF1000,1000_QL80_.jpg",
    "genre": ["Animation", "Adventure", "Drama"],
    "rate": 8.5
}

### UPDATE PATCH
PATCH http://localhost:4000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0 HTTP/1.1
Content-Type: application/json

{
    "year": 1990
}

### DELETE A MOVIE
DELETE http://localhost:4000/movies/33e8d638-f156-11ef-982c-45394dd74f04 HTTP/1.1
Content-Type: application/json