### GET ALL MOVIES
GET http://localhost:4000/movies HTTP/1.1

### GET MOVIE BY ID
GET http://localhost:4000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf HTTP/1.1

### GET MOVIES BY GENRE
GET http://localhost:4000/movies?genre=Terror HTTP/1.1

###CREATE A MOVIE
POST http://localhost:4000/movies HTTP/1.1
Content-Type: application/json

{
    "title": "Ignacio",
    "year": 1994,
    "director": "Sepulveda",
    "duration": 88,
    "poster": "https://m.media-amazon.com/images/I/81BMmrwSFOL._AC_UF1000,1000_QL80_.jpg",
    "genre": ["Animation", "Adventure", "Drama"],
    "rate": 8.5
}

### UPDATE PATCH
PATCH http://localhost:4000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
    "year": 1990
}